services:
  app:
    container_name: blog
    build:
      context: .
      dockerfile: prod.Dockerfile
    expose:
      - "3000"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env

  redis:
    image: redis:8-alpine
    expose:
      - "6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data

volumes:
  redis-data:
